### ISSUE TITLE
Feature Request: Support for Account and Network Change Listeners

### ISSUE THREAD

**Issue by stoXmod** [secretkeylabs/sats-connect#117] opened 2024-04-23 14:49 UTC
### Description

In the Unisat wallet, we can listen for account and network changes using the following event listeners:

```
unisat.on('accountsChanged', handleAccountsChanged);
unisat.on('networkChanged', handleNetworkChanged);
```

This feature is crucial for maintaining the app's responsiveness to changes in the user's wallet settings, such as switching accounts or networks, which is common in blockchain applications.

### Solution

I suggest adding support for event listeners in the Xverse wallet that can handle 'accountsChanged' and 'networkChanged' events. This would make the wallet more versatile and user-friendly, particularly for applications that need to react in real-time to changes in the user's wallet configuration.

Ideally, the implementation would allow developers to use event listeners similar to those in Unisat.

```
xverse.on('accountsChanged', handleAccountsChanged);
xverse.on('networkChanged', handleNetworkChanged);

```

Benefits:

- Enhances user experience by allowing real-time application updates in response to wallet changes.
- Aligns Xverse wallet's functionality with other popular wallets like Unisat, potentially increasing its adoption.
- Supports developers in building more robust and interactive blockchain applications.

**Comment by stoXmod** [comment] 2024-04-23 14:51
I would love to hear, if is there currently any workaround for this. 🤔

**Comment by teebszet** [comment] 2024-05-29 04:46
hi @stoXmod, thanks for the suggestion!

I can confirm this is in our roadmap and will be included very soon 👀

**Comment by teebszet** [comment] 2024-05-29 04:52
duplicate of: https://github.com/secretkeylabs/sats-connect/issues/54

**Closed as completed by teebszet** 2024-05-29 04:52 UTC
Labels: duplicate, enhancement
